"""
Converts the JSON rules files (used by the frontend) into structured, readable
Markdown for the AI. The generated Markdown is ingested into the RAG (ChromaDB),
allowing the Game Master to authoritatively consult rules, classes, races, spells
and equipment.

Same data source, two representations:
  - JSON  → frontend (dropdowns, tooltips)
  - Markdown → AI (header-based chunking + RAG)

Run: python -m backend.rag_system.build_rules_md
"""
import os
import re
import sys
import html
import json

# Allows running both as a module (-m) and as a direct script
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from backend.data_manager import (
    BASE_DIR, RACES_FILE, CLASSES_FILE, SPELLS_FILE, EQUIPMENT_FILE, ABILITIES_FILE
)

RULES_MD_DIR = os.path.join(BASE_DIR, "DATA", "rules_md")

_GENERATED_NOTE = "<!-- AUTO-GENERATED by build_rules_md.py — do not edit by hand. -->\n\n"

_ATTR_NAMES = {
    "strength": "Strength", "dexterity": "Dexterity", "constitution": "Constitution",
    "intelligence": "Intelligence", "wisdom": "Wisdom", "charisma": "Charisma",
}
_ARMOR_NAMES = {"light": "light", "medium": "medium", "heavy": "heavy", "shield": "shield"}


def _clean(text: str) -> str:
    """Strips HTML markup from descriptions, preserving the text and the span label."""
    if not text:
        return ""
    text = text.replace("</span>", " — ")
    text = re.sub(r"<[^>]+>", "", text)
    text = html.unescape(text)
    text = re.sub(r"\s+", " ", text).strip()
    text = re.sub(r"^\s*—\s*", "", text)        # empty span at the start
    text = re.sub(r"\s*—\s*$", "", text)         # dangling separator at the end
    return text


def _load(path: str) -> dict:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def build_classes_md() -> str:
    data = _load(CLASSES_FILE)
    classes = data.get("classes", {})
    descriptions = data.get("descriptions", {})

    lines = [_GENERATED_NOTE, "# D&D 5e Classes\n"]
    for name, cls in classes.items():
        lines.append(f"## {name}")
        hd = cls.get("hit_dice")
        profs = ", ".join(cls.get("proficiencies", [])) or "—"
        lines.append(f"**Hit Die:** d{hd} | **Skill Proficiencies:** {profs}\n")

        feats_by_level = cls.get("features", {})
        if feats_by_level:
            lines.append("**Features by Level:**")
            for lvl in sorted(feats_by_level, key=lambda k: int(k)):
                feats = ", ".join(feats_by_level[lvl])
                lines.append(f"- Level {lvl}: {feats}")
            lines.append("")

        # Detail only the features of this class that have a description
        all_feats = [f for fs in feats_by_level.values() for f in fs]
        detailed = [(f, descriptions[f]) for f in all_feats if f in descriptions]
        if detailed:
            lines.append("**Feature Details:**")
            for feat, desc in detailed:
                lines.append(f"- **{feat}:** {_clean(desc)}")
            lines.append("")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def build_races_md() -> str:
    data = _load(RACES_FILE)
    races = data.get("races", {})
    descriptions = data.get("descriptions", {})

    lines = [_GENERATED_NOTE, "# D&D 5e Races\n"]
    for name, race in races.items():
        lines.append(f"## {name}")
        attrs = race.get("attributes", {})
        if attrs:
            bonus = ", ".join(f"{_ATTR_NAMES.get(k, k)} +{v}" for k, v in attrs.items())
        else:
            bonus = "—"
        lines.append(f"**Ability Score Bonus:** {bonus}\n")

        feats = race.get("features", [])
        if feats:
            lines.append(f"**Racial Traits:** {', '.join(feats)}\n")

        detailed = [(f, descriptions[f]) for f in feats if f in descriptions]
        if detailed:
            lines.append("**Trait Details:**")
            for feat, desc in detailed:
                lines.append(f"- **{feat}:** {_clean(desc)}")
            lines.append("")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def build_spells_md() -> str:
    data = _load(SPELLS_FILE)
    by_level = data.get("spells_by_level", {})
    descriptions = data.get("descriptions", {})

    lines = [_GENERATED_NOTE, "# D&D 5e Spells\n"]
    for lvl in sorted(by_level, key=lambda k: int(k)):
        lines.append(f"## Level {lvl} Spells")
        for spell in by_level[lvl]:
            desc = _clean(descriptions.get(spell, ""))
            lines.append(f"- **{spell}:** {desc}" if desc else f"- **{spell}**")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _format_item(name: str, item: dict) -> str:
    desc = item.get("description", "").strip()
    status = item.get("status", {}) or {}
    specs = []

    if "damage" in status:
        dmg = status["damage"]
        dtype = status.get("damage_type", "")
        specs.append(f"Damage: {dmg} {dtype}".strip())
    if status.get("properties"):
        specs.append(f"Properties: {', '.join(status['properties'])}")
    if "base_ac" in status:
        atype = _ARMOR_NAMES.get(status.get("armor_type", ""), status.get("armor_type", ""))
        specs.append(f"Base AC: {status['base_ac']} ({atype} armor)")
    if status.get("ac_bonus"):
        specs.append(f"AC Bonus: +{status['ac_bonus']}")
    if status.get("strength_req"):
        specs.append(f"Requires Strength {status['strength_req']}")
    if status.get("stealth_disadvantage"):
        specs.append("Disadvantage on Stealth")
    if status.get("healing"):
        specs.append(f"Healing: {status['healing']}")

    spec_str = f" ({'; '.join(specs)})" if specs else ""
    return f"- **{name}**: {desc}{spec_str}"


def build_equipment_md() -> str:
    data = _load(EQUIPMENT_FILE)
    items = data.get("items", {})

    # Group by type in a stable order
    groups: dict[str, list[str]] = {}
    for name, item in items.items():
        groups.setdefault(item.get("type", "Other"), []).append(name)

    type_order = ["Weapon", "Armor", "Shield", "Consumable", "Misc"]
    type_titles = {"Weapon": "Weapons", "Armor": "Armor", "Shield": "Shields",
                   "Consumable": "Consumables", "Misc": "Miscellaneous Items"}

    ordered = [t for t in type_order if t in groups] + [t for t in groups if t not in type_order]

    lines = [_GENERATED_NOTE, "# D&D 5e Equipment\n"]
    for t in ordered:
        lines.append(f"## {type_titles.get(t, t)}")
        for name in groups[t]:
            lines.append(_format_item(name, items[name]))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def build_abilities_md() -> str:
    data = _load(ABILITIES_FILE)
    descriptions = data.get("descriptions", {})
    if not descriptions:
        return ""
    lines = [_GENERATED_NOTE, "# Miscellaneous Abilities\n", "## Ability Reference"]
    for name, desc in descriptions.items():
        lines.append(f"- **{name}:** {_clean(desc)}")
    lines.append("")
    return "\n".join(lines).rstrip() + "\n"


_BUILDERS = {
    "classes.md": build_classes_md,
    "races.md": build_races_md,
    "spells.md": build_spells_md,
    "equipment.md": build_equipment_md,
    "abilities.md": build_abilities_md,
}


def build_all_rules_md() -> list[str]:
    """Generates all Markdown files from the JSON. Returns the written paths."""
    os.makedirs(RULES_MD_DIR, exist_ok=True)
    written = []
    for filename, builder in _BUILDERS.items():
        content = builder()
        if not content.strip():
            continue
        path = os.path.join(RULES_MD_DIR, filename)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        written.append(path)
    print(f"[build_rules_md] {len(written)} Markdown file(s) generated in {RULES_MD_DIR}")
    return written


if __name__ == "__main__":
    build_all_rules_md()
